-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 09, 2025 at 09:38 AM
-- Server version: 11.8.3-MariaDB-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u622340404_royalmaids`
--

-- --------------------------------------------------------

--
-- Table structure for table `maid_evaluations`
--

CREATE TABLE `maid_evaluations` (
  `id` int(11) NOT NULL,
  `trainer_id` int(11) NOT NULL,
  `facilitator` varchar(100) DEFAULT NULL,
  `status` varchar(32) DEFAULT 'pending',
  `observation_date` date DEFAULT NULL,
  `trainee_name` varchar(100) DEFAULT NULL,
  `confidence` tinyint(4) DEFAULT NULL,
  `confidence_comment` text DEFAULT NULL,
  `self_awareness` tinyint(4) DEFAULT NULL,
  `self_awareness_comment` text DEFAULT NULL,
  `emotional_stability` tinyint(4) DEFAULT NULL,
  `emotional_stability_comment` text DEFAULT NULL,
  `growth_mindset` tinyint(4) DEFAULT NULL,
  `growth_mindset_comment` text DEFAULT NULL,
  `punctuality` tinyint(4) DEFAULT NULL,
  `punctuality_comment` text DEFAULT NULL,
  `respect` tinyint(4) DEFAULT NULL,
  `respect_comment` text DEFAULT NULL,
  `ownership` tinyint(4) DEFAULT NULL,
  `ownership_comment` text DEFAULT NULL,
  `conduct` tinyint(4) DEFAULT NULL,
  `conduct_comment` text DEFAULT NULL,
  `cleaning` tinyint(4) DEFAULT NULL,
  `cleaning_comment` text DEFAULT NULL,
  `laundry` tinyint(4) DEFAULT NULL,
  `laundry_comment` text DEFAULT NULL,
  `meals` tinyint(4) DEFAULT NULL,
  `meals_comment` text DEFAULT NULL,
  `childcare` tinyint(4) DEFAULT NULL,
  `childcare_comment` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `cleaning_q1` tinyint(4) DEFAULT NULL,
  `cleaning_q1_comment` text DEFAULT NULL,
  `cleaning_q2` tinyint(4) DEFAULT NULL,
  `cleaning_q2_comment` text DEFAULT NULL,
  `cleaning_q3` tinyint(4) DEFAULT NULL,
  `cleaning_q3_comment` text DEFAULT NULL,
  `cleaning_q4` tinyint(4) DEFAULT NULL,
  `cleaning_q4_comment` text DEFAULT NULL,
  `cleaning_q5` tinyint(4) DEFAULT NULL,
  `cleaning_q5_comment` text DEFAULT NULL,
  `laundry_q1` tinyint(4) DEFAULT NULL,
  `laundry_q1_comment` text DEFAULT NULL,
  `laundry_q2` tinyint(4) DEFAULT NULL,
  `laundry_q2_comment` text DEFAULT NULL,
  `laundry_q3` tinyint(4) DEFAULT NULL,
  `laundry_q3_comment` text DEFAULT NULL,
  `laundry_q4` tinyint(4) DEFAULT NULL,
  `laundry_q4_comment` text DEFAULT NULL,
  `laundry_q5` tinyint(4) DEFAULT NULL,
  `laundry_q5_comment` text DEFAULT NULL,
  `laundry_q6` tinyint(4) DEFAULT NULL,
  `laundry_q6_comment` text DEFAULT NULL,
  `meals_q1` tinyint(4) DEFAULT NULL,
  `meals_q1_comment` text DEFAULT NULL,
  `meals_q2` tinyint(4) DEFAULT NULL,
  `meals_q2_comment` text DEFAULT NULL,
  `meals_q3` tinyint(4) DEFAULT NULL,
  `meals_q3_comment` text DEFAULT NULL,
  `meals_q4` tinyint(4) DEFAULT NULL,
  `meals_q4_comment` text DEFAULT NULL,
  `meals_q5` tinyint(4) DEFAULT NULL,
  `meals_q5_comment` text DEFAULT NULL,
  `meals_q6` tinyint(4) DEFAULT NULL,
  `meals_q6_comment` text DEFAULT NULL,
  `meals_q7` tinyint(4) DEFAULT NULL,
  `meals_q7_comment` text DEFAULT NULL,
  `meals_q8` tinyint(4) DEFAULT NULL,
  `meals_q8_comment` text DEFAULT NULL,
  `childcare_q1` tinyint(4) DEFAULT NULL,
  `childcare_q1_comment` text DEFAULT NULL,
  `childcare_q2` tinyint(4) DEFAULT NULL,
  `childcare_q2_comment` text DEFAULT NULL,
  `childcare_q3` tinyint(4) DEFAULT NULL,
  `childcare_q3_comment` text DEFAULT NULL,
  `childcare_q4` tinyint(4) DEFAULT NULL,
  `childcare_q4_comment` text DEFAULT NULL,
  `childcare_q5` tinyint(4) DEFAULT NULL,
  `childcare_q5_comment` text DEFAULT NULL,
  `childcare_q6` tinyint(4) DEFAULT NULL,
  `childcare_q6_comment` text DEFAULT NULL,
  `childcare_q7` tinyint(4) DEFAULT NULL,
  `childcare_q7_comment` text DEFAULT NULL,
  `childcare_q8` tinyint(4) DEFAULT NULL,
  `childcare_q8_comment` text DEFAULT NULL,
  `childcare_q9` tinyint(4) DEFAULT NULL,
  `childcare_q9_comment` text DEFAULT NULL,
  `childcare_q10` tinyint(4) DEFAULT NULL,
  `childcare_q10_comment` text DEFAULT NULL,
  `security_q1` tinyint(4) DEFAULT NULL,
  `security_q1_comment` text DEFAULT NULL,
  `security_q2` tinyint(4) DEFAULT NULL,
  `security_q2_comment` text DEFAULT NULL,
  `security_q3` tinyint(4) DEFAULT NULL,
  `security_q3_comment` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `maid_evaluations`
--

INSERT INTO `maid_evaluations` (`id`, `trainer_id`, `facilitator`, `status`, `observation_date`, `trainee_name`, `confidence`, `confidence_comment`, `self_awareness`, `self_awareness_comment`, `emotional_stability`, `emotional_stability_comment`, `growth_mindset`, `growth_mindset_comment`, `punctuality`, `punctuality_comment`, `respect`, `respect_comment`, `ownership`, `ownership_comment`, `conduct`, `conduct_comment`, `cleaning`, `cleaning_comment`, `laundry`, `laundry_comment`, `meals`, `meals_comment`, `childcare`, `childcare_comment`, `created_at`, `cleaning_q1`, `cleaning_q1_comment`, `cleaning_q2`, `cleaning_q2_comment`, `cleaning_q3`, `cleaning_q3_comment`, `cleaning_q4`, `cleaning_q4_comment`, `cleaning_q5`, `cleaning_q5_comment`, `laundry_q1`, `laundry_q1_comment`, `laundry_q2`, `laundry_q2_comment`, `laundry_q3`, `laundry_q3_comment`, `laundry_q4`, `laundry_q4_comment`, `laundry_q5`, `laundry_q5_comment`, `laundry_q6`, `laundry_q6_comment`, `meals_q1`, `meals_q1_comment`, `meals_q2`, `meals_q2_comment`, `meals_q3`, `meals_q3_comment`, `meals_q4`, `meals_q4_comment`, `meals_q5`, `meals_q5_comment`, `meals_q6`, `meals_q6_comment`, `meals_q7`, `meals_q7_comment`, `meals_q8`, `meals_q8_comment`, `childcare_q1`, `childcare_q1_comment`, `childcare_q2`, `childcare_q2_comment`, `childcare_q3`, `childcare_q3_comment`, `childcare_q4`, `childcare_q4_comment`, `childcare_q5`, `childcare_q5_comment`, `childcare_q6`, `childcare_q6_comment`, `childcare_q7`, `childcare_q7_comment`, `childcare_q8`, `childcare_q8_comment`, `childcare_q9`, `childcare_q9_comment`, `childcare_q10`, `childcare_q10_comment`, `security_q1`, `security_q1_comment`, `security_q2`, `security_q2_comment`, `security_q3`, `security_q3_comment`) VALUES
(42, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-13', 'Simmie Adong', 4, 'She expresses herself fairly well', 2, 'Still lacks on some basics like strengths and weaknesses', 4, 'Emotionally stable', 3, 'Her mindset is fairly mature', 2, 'She poorly performed regarding the tasks we had within the class', 4, 'Fairly follows through though she needs to understand the instructions well. It may involve repeating for her', 3, 'She owns up to her work well.', 4, 'Good interpersonal conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-13 13:47:02', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 1, 'Not yet good at this.', 2, 'Still learning. She only has the local methods.', 2, 'She is still learning'),
(43, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-15', 'Simmie Adong', 5, 'Her attitude towards work is good', 3, 'Fairly.good due to lack of xommunication', 5, 'Very good and she understands', 5, 'Her willingness to learn makes her stand out.', 5, 'She is good', 5, 'She accomplishs task with easy and accomplishes them', 5, 'Simmie loves doing what she is given to.do without hastitation', 5, 'She is a good relation person.she fits well and works.well.with others', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-15 07:48:43', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'She is good', 3, 'Her verbal is lacking but.she is good with non.verbal communication', 4, 'She has a good sense of observation.', 4, 'She is good with monitoring and instructing in deed', 5, 'She is practical ', 5, 'Shr is clean as a person ', 5, 'She has a sharp her', 5, 'She is patient', 3, 'Her verbal communication is lacking', 3, 'Simmie can only write her reading is still wanting.', 0, '', 0, '', 0, ''),
(44, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-15', 'Simmie Adong', 5, 'Very settled ', 4, 'She knows who she is.', 5, 'She is easily manages her emotions  without causing an outburst', 5, 'She believes her growth can be achieved by learning more ', 5, 'She complets her tasks on time and comes on time in class', 5, 'Very good', 4, 'She has a good sense of adaptability', 5, 'She relatives well with her mates', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-15 09:22:14', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Good with children', 4, 'Fairly good', 5, 'Very active ', 4, 'She has shown practical  examples by how she inyeracts with our own vicky', 5, 'She has a wide range of games when given opportunity ', 5, 'Good her personal hygiennee shows it', 4, 'Good', 5, 'Excellent', 4, 'She is good with non verbal   leadership abilities than spoken', 3, 'She can write but cant read properly.', 0, '', 0, '', 0, ''),
(45, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-18', 'Robina Akao', 1, 'Takes some time to express themselves. Often covers her face when sharing.', 2, 'Knows few aspects she knows about self', 3, 'Stable', 3, 'Moderate', 4, 'Fairly good time manager', 4, 'Respects instructions ', 3, 'Has a good sense of ownership', 3, 'Good. Fair for new faces', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-18 15:07:43', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Fairly good', 2, 'Still at the learning stage.', 3, 'She is fairly conscious '),
(46, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-18', 'Simmie Adong', 2, 'Fairly good. Takes a while to communicate. But speaks more frequently in her mother tongue', 2, 'Fairly aware', 3, 'Stable', 3, 'Mature ', 4, 'Time management improved from the last class', 3, 'Good', 3, 'Owns up to her work.', 4, 'Good interpersonal conduct ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-18 15:16:06', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Fairly alert', 1, 'Still learning', 3, 'Fairly conscious'),
(47, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-18', 'Pauline Awori Mary ', 4, 'freely expresses herself', 4, 'strong sense of awareness', 5, 'stable', 4, 'grown', 5, 'punctual', 5, 'carefully follows through instructions', 3, 'fairly good', 4, 'good interpersonal conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-19 16:54:06', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'alert', 3, 'has knowledge regarding the same', 3, 'conscious'),
(48, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Concy Ajok', 3, 'Relatively bold', 4, 'She can speak out the things that she stands for', 4, 'Positively receives correction ', 5, 'She is will to learn', 5, 'She keeps time for the class', 4, 'She respects instructions ', 4, 'She purposes to accomplish her tasks', 4, 'She relates well with others', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 07:15:49', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'She knows how to cook some foods in the central.', 4, 'She is watchful of the cleanliness of the kitchen environment ', 3, 'She is improving on  how to plan', 3, 'She is learning the various kitchen equipment ', 3, 'Still needs more knowledge on nutrition ', 4, 'Still needs more knowledge', 4, 'Knows how to use most of the kitchen equipment ', 3, 'Still learning ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(49, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Harriet Asemo', 4, 'She is bold', 4, 'He can speak about her self', 4, 'Emotionally stable', 4, 'She is willing to learn', 4, 'She keeps time for the training ', 4, 'She respects instructions', 4, 'She takes charge of her work ', 4, 'She relates and respects other people', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 07:28:53', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is knowledgeable about the foods in the entral', 4, 'She is watchful of a clean environment ', 3, 'She is learning how to plan meals', 3, 'She is learning', 4, 'She is knowledgeable ', 4, 'Good ', 3, 'She is learning ', 3, 'She is learning', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(50, 14, 'Esther Akello', 'approved', '2025-08-20', 'Innocent Lalam', 3, 'Seem a little low spirited today', 2, '', 3, 'Needs to be encouraged more', 2, 'Her growth mindset will solely depend on her emotional well being', 3, 'Average', 1, 'She did put her head down in class the entire time', 2, 'Promising', 3, 'She is able to relate with her colleagues fairly', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 10:37:42', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 1, 'Not assessed ', 2, 'Can read and write(assumed)', 0, '', 0, '', 0, ''),
(51, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-20', 'Pauline Awori Mary ', 5, 'She is good', 5, 'Her confidence is high on self', 5, 'Very good', 5, 'Very receptive and willing to adjust .', 5, 'Always on time', 5, 'Helps out to coordinate others', 5, 'She is also self driven', 5, 'Has good team spirit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 12:51:00', 4, 'Good', 5, 'Perfect', 5, ' Very good for the ones she knows', 5, 'She understands the detergent.', 5, 'Good.', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(52, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-20', 'Pauline Awori Mary ', 5, 'She is good', 5, 'Her confidence is high on self', 5, 'Very good', 5, 'Very receptive and willing to adjust .', 5, 'Always on time', 5, 'Helps out to coordinate others', 5, 'She is also self driven', 5, 'Has good team spirit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 12:51:02', 4, 'Good', 5, 'Perfect', 5, ' Very good for the ones she knows', 5, 'She understands the detergent.', 5, 'Good.', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(53, 14, 'Esther Akello', 'approved', '2025-08-20', 'Concy Ajok', 5, 'She is confident', 5, 'She is smart and neat', 5, 'Emotional stable', 5, 'Willing to learn and unlearn things', 5, 'Very good time manager', 5, 'Listens and adheres to instructions', 5, 'Ready to sharpen herself more', 5, 'Good and bonding and interacting with her colleagues ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-20 13:43:03', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'She has a good understanding of how to nature and support children(to be assessed more)', 4, 'She\'s able to communicate and bond well with children', 3, 'To be further assessed ', 3, 'To be further assessed ', 3, 'To be further assessed', 3, 'To be accessed ', 4, 'She\'s able to observe the varying changes in a child', 4, 'She\'s able to adapt and understand a child based on their emotional status', 4, 'She\'s able to teach  and instruct a child', 3, 'She\'s able to read and understand verbal communication.', 0, '', 0, '', 0, ''),
(54, 14, 'Esther Akello', 'approved', '2025-08-22', 'Concy Ajok', 5, 'She is confident', 5, 'Self conscious ', 5, 'She is emotionally stable', 5, 'Ready to learn and grow', 4, 'I was a bit late today ', 5, 'Listens to set instructions and is willing to follow', 4, 'Ready to work well', 5, 'Has a good relation with her peers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 11:21:20', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'She shows and understanding of care and support', 4, 'She is willing to listen to the child and understand their perpective', 3, 'Not yet assessed ', 3, 'Not assessed ', 4, 'She can engage and play with a child during role play', 5, 'Well balanced', 4, 'Can observe and see the different changes in a child', 5, 'She can adapt to a child\'s changing need', 4, 'She is able to instruct and teach well', 3, 'Yet to observe.', 0, '', 0, '', 0, ''),
(55, 14, 'Esther Akello', 'approved', '2025-08-22', 'Flavia Ajalo', 5, 'Flavia is confident and has good communication ', 4, 'She is smart and neat', 5, 'Emotionally stable and relaxed', 4, 'Ready to learn and grow', 4, 'She was on time ', 4, 'She listens to instructions and is ready to learn', 5, 'Ready to work', 5, 'She relates well with her peers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 11:30:27', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Flavia is caring and emotionally stable', 5, 'She interacts well with children', 4, 'She can play well with the child and supervise their well being', 3, 'To be assessed ', 4, 'She can engage a child well', 3, 'To be assessed ', 4, 'She can observe changes in children', 4, 'She is willing to adapt  accordingly ', 4, 'She can instruct a child well', 3, 'To be assessed ', 0, '', 0, '', 0, ''),
(56, 14, 'Esther Akello', 'approved', '2025-08-22', 'Harriet Asemo', 5, 'Harriet is confident ', 4, 'She is neat and smart', 3, 'Today she seems low spirited.', 4, 'Ready to learn and grow', 4, 'She needs to improve on her time management ', 4, 'She can do better', 4, 'Ready to work', 5, 'Harriet has a good relation with her peers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 11:36:54', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is emotionally stable', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 4, 'She has understood how to adapt to the changing needs of children', 4, 'I believe she is able to instruct a child the right way', 3, 'To be assessed ', 0, '', 0, '', 0, ''),
(57, 14, 'Esther Akello', 'approved', '2025-08-22', 'Innocent Lalam', 4, 'Innocent has shown an improvement ', 4, 'She is becoming more aware of her surroundings ', 4, 'She is becoming more emotionally stable ', 4, 'Her work mentality is starting to shift hence a boost in her growth ', 4, 'She came to class on time today', 4, 'She2as able to listen and pay attention during class', 3, 'More effort still is required herein', 4, 'She relates well with her friends and peers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 11:47:49', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is calm and collected which makes it a good start in positive intending in child development ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be assessed ', 3, 'To be asses', 4, 'She is starting to open up to her surrounding which will be a plus in observing changes in a child', 3, 'To be assessed ', 3, 'She ought to learn more on how to instruct the child and be the adult on the house', 3, 'To be assessed ', 0, '', 0, '', 0, ''),
(58, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Semmy Adong', 2, 'Low confidence', 2, 'Fairly aware', 4, 'Stable', 3, 'Mature', 3, 'Punctual', 3, 'Good', 3, 'Good', 3, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:22:51', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Good', 3, 'Improving', 3, 'Improving'),
(59, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Sandra Ayot', 4, 'Openly shares when asked', 3, 'Aware of her strength and weakness', 5, 'Stable', 5, 'Steadily mature', 4, 'Punctual', 4, 'Respects instructions all through', 4, 'Owns up to work', 5, 'Good interpersonal conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:26:08', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fairly alert', 3, 'Improving', 4, 'Steadily canscious'),
(60, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Robina Akao', 2, 'Needs improvement. Though she fairly expresses herself better in her local language', 3, 'Self aware', 4, 'Stable', 3, 'Fairly mature', 3, 'Punctual', 3, 'Follows instructions ', 3, 'Owns up to work', 4, 'Good conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:28:52', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Fair', 2, 'Improving', 2, 'Moderately conscious.'),
(61, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Innocent Lalam', 1, 'Poor needs improvement. Never answered any question asked in class', 2, 'Needs improvement ', 4, 'Stable', 3, 'Fairly mature', 3, 'Moderately good', 2, 'Needs improvement ', 2, 'Fair performance', 4, 'Good interpersonal conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:31:28', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 1, 'Still lacking', 1, 'Still lacking', 2, 'Needs improvement '),
(62, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Harriet Asemo', 3, 'Express herself fairly well', 3, 'Aware', 4, 'Stable', 4, 'Mature', 2, 'Fairly good', 4, 'Respects instructions well', 3, 'Owns up to work', 4, 'Good conduct', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:34:11', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Good ', 3, 'Improving', 3, 'Conscious'),
(63, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Flavia Ajalo', 4, 'Good. She was one of the active students', 4, 'She is aware of herself', 4, 'Stable', 4, 'Mature mindset', 2, 'Fair', 4, 'Follows instructions', 4, 'Owns work pretty well', 5, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:36:03', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Alert', 3, 'Improving', 3, 'Conscious '),
(64, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-22', 'Concy Ajok', 4, 'Confident and assertive ', 4, 'Self aware. She hates being shouted at. Same as for Flavia. ', 2, 'Showed aspects of short temper. One member commented about it too.', 3, 'Moderately mature', 2, 'Fairly mature', 4, 'Follows instructions', 2, 'Owns up to her work', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-22 15:39:54', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fairly alert', 3, 'Improving has traditional ways to first aid', 3, 'Cons ious'),
(65, 14, 'Esther Akello', 'approved', '2025-08-22', 'Semmy Adong', 4, 'She can do better and grow her confidence ', 4, 'Needs to interact more, she\'s been down lately', 3, 'She can do better', 4, 'She is willing to grow', 3, 'She developing a down ward trend in managing her time well', 4, 'She can do better', 4, 'She can do better', 4, 'She relates well with her friends', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-25 11:35:14', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Very friendly', 5, 'She is good with young children', 4, 'She likes to relate and play with them well.', 3, 'She is learning and will do better', 3, 'She can do better ', 4, 'She can do better', 3, 'She is attentive to the child\'s needs', 3, 'To be observed', 3, 'To be observed ', 3, 'To be observed', 0, '', 0, '', 0, ''),
(66, 14, 'Esther Akello', 'approved', '2025-08-25', 'Pauline Awori Mary ', 5, 'Confident ', 5, 'Self awareness', 5, 'Emotionally stable', 5, 'Willing to work', 5, 'Was in class on time', 5, 'Listens well', 5, 'Ready to work', 5, 'Relates well with her friends', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 06:48:13', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Cares for children', 5, 'Knows how to hold her conversation with children', 5, 'Cares for children', 4, 'She is learning better positive disciplining techniques', 5, 'She is able to engage a child ', 4, 'She can keep a child neat and clean', 4, 'She can observe changes in a child', 4, 'She is cheerful and able to adapt to the child\'s needs', 5, 'She is able to teach children', 4, 'She can read and write.', 0, '', 0, '', 0, ''),
(67, 14, 'Esther Akello', 'approved', '2025-08-25', 'Harriet Asemo', 5, 'She is confident ', 4, 'She know how well she feels', 5, 'She is calm and well balanced', 4, 'She is ready to try new things', 4, 'She was in class on time', 4, 'She is able to listen to instructions ', 4, 'She has a good work attitude ', 4, 'She relates well with her mates', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 07:33:49', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is able to care for others', 4, 'She is able to interact well with children', 4, 'She has learnt safety modes at home', 4, 'Shr is learning. Positive displining technques', 4, 'She can play positively with children', 4, 'She has learnt hygiene methods', 4, 'She is ', 4, 'She is flexible and can adapt  accordingly ', 4, 'She is learning how to teach children well', 3, 'To be observed', 0, '', 0, '', 0, ''),
(68, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Pauline Awori Mary ', 5, 'She freely expresses herself ', 4, 'She knows what she is good at', 4, 'She is receptive of correction ', 4, 'She is positive about learning ', 5, 'She keeps time', 4, 'She honors instructions ', 5, 'She takes charge of her responsibilities', 5, 'She relates well with her friends ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:09:01', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is knowledgeable about cooking ', 4, 'She is critical about kitchen cleanliness ', 4, 'She is knowledgeable about the different meal groups', 4, 'She is knowledgeable ', 4, 'She is knowledgeable ', 4, 'She is knowledgeable ', 3, 'She knows how to use some', 4, 'She is knowledgeable ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(69, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Concy Ajok', 4, 'She knows  what to do', 4, 'She is responsible for her feelings', 5, 'Good', 5, 'Open to learn', 3, 'Fair', 3, 'Reluctant', 4, 'Fair', 5, 'Good with others', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:12:45', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good', 4, 'Good whrn told', 4, 'Good obervation skills', 5, 'Very good', 4, 'Good', 5, 'Very good', 5, 'Good', 5, 'Very good', 5, 'Good', 4, 'Good', 0, '', 0, '', 0, ''),
(70, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Sandra Ayot', 4, 'She is confident ', 4, 'She is well versed with what\'s he likes', 4, 'She positively receives correction ', 4, 'She is positive about learning ', 5, 'She is very punctual', 5, 'She abides by the instructions give to her', 5, 'She owns her work', 5, 'Respects orhers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:16:09', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She is knowledgeable ', 4, 'She is clean', 4, 'She is knowledgeable ', 4, 'She is knowledgeable ', 3, 'She is knowledgeable ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(71, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Flavia Ajalo', 5, 'She is confident ', 4, 'She knows what she wants ', 3, 'Fair', 3, 'Slightly positive about learning ', 3, 'Fair', 3, 'Takes time to execute instructions ', 3, 'Fair', 3, 'She is a quiet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:21:20', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Learning the way food in the central is cooked', 4, 'She is clean', 4, 'She knowledgeable about food groups', 4, 'Good ', 4, 'Good ', 4, 'Good', 4, 'Knowledgeable ', 4, 'Knowledgeable ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(72, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Robina Akao', 3, 'Fairly confident ', 3, 'Fair', 4, 'Fair', 4, 'She is willing to learn', 4, 'Fair', 4, 'Good ', 4, 'Good ', 4, 'Interacts well with other people ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:26:31', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fair', 3, 'Fair', 3, 'Fair ', 3, 'Fai', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(73, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Semmy Adong', 3, 'Fair', 3, 'Fair', 3, 'Fair', 4, 'She is willing to learn', 4, 'Good ', 4, 'Good ', 4, 'Good ', 5, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:30:46', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good ', 4, 'Good ', 3, 'Fair', 3, 'Fair', 3, 'Fair ', 3, 'Fair', 3, 'Fair', 3, 'Fair', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(74, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-19', 'Innocent Lalam', 2, 'Low confidence ', 2, 'Low', 3, 'Fair ', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair', 2, 'She is is quiet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:45:05', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fair ', 3, 'Fair ', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair ', 2, 'Poor', 2, 'Low', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(75, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Pauline Awori Mary ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Positive about growth ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:52:04', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good ', 5, 'Good', 5, 'Good ', 5, 'Good ', 5, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(76, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Concy Ajok', 4, 'Good', 4, 'Good', 5, 'Very good', 5, 'She is good and open to learn', 3, 'Fair', 3, 'Fairly good', 4, 'Good', 5, 'Very good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:54:27', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good', 4, 'Good', 5, 'Very good', 5, 'Very good', 4, 'Good', 5, 'Very good', 4, 'Good', 5, 'Bery good', 5, 'Excellent', 4, 'Hood', 0, '', 0, '', 0, ''),
(77, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Sandra Ayot', 5, 'Good ', 4, 'Good ', 4, 'Good', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 10:57:20', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 4, 'Good ', 5, 'Good ', 5, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(78, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Harriet Asemo', 4, 'Good', 5, 'Very good', 5, 'Excellent', 5, 'Excellent', 4, 'Good', 5, 'Excellent', 5, 'Excellent', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 11:58:15', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good', 4, 'Good', 4, 'Good', 4, 'Fairly good', 3, 'Fail', 5, 'Excellent', 4, 'Good', 5, 'Good', 4, 'Good', 5, 'Excellent', 0, '', 0, '', 0, ''),
(79, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Harriet Asemo', 5, 'Good ', 4, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 4, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:03:34', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 5, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(80, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Innocent Lalam', 1, 'Poor in expression', 1, 'Poor', 2, 'Poor', 3, 'Fair', 1, 'Poor', 1, 'Poor', 4, 'Kinder fair', 3, 'Fairly good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:05:15', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Poor', 1, 'Poor', 2, 'Poor', 2, 'Poor', 2, 'Poor', 2, 'Not good', 1, 'Not good', 2, 'Poor', 1, 'Poor', 3, 'Fair', 0, '', 0, '', 0, ''),
(81, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Innocent Lalam', 1, 'Poor in expression', 1, 'Poor', 2, 'Poor', 3, 'Fair', 1, 'Poor', 1, 'Poor', 4, 'Kinder fair', 3, 'Fairly good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:05:15', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Poor', 1, 'Poor', 2, 'Poor', 2, 'Poor', 2, 'Poor', 2, 'Not good', 1, 'Not good', 2, 'Poor', 1, 'Poor', 3, 'Fair', 0, '', 0, '', 0, ''),
(82, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Pauline Awori Mary ', 5, 'Good', 5, 'Excellent', 5, 'Excellent', 5, 'Excellent', 5, 'Excellent', 5, 'Very good', 5, 'Excellent', 5, 'Very good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:08:25', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Excellent', 5, 'Excellent', 5, 'Very good', 5, 'Good', 5, 'Good', 5, 'Very good', 5, 'Excellent', 5, 'Excellent', 5, 'Very good', 5, 'Very good', 0, '', 0, '', 0, ''),
(83, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Concy Ajok', 4, 'Improved', 3, 'Fair', 4, 'Good ', 3, 'Fair', 3, 'Fair', 3, 'Delays to yield to instructions ', 3, 'Slow', 4, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:11:48', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(84, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Robina Akao', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair ', 3, 'Fair ', 3, 'Fair ', 4, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:15:55', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fair ', 3, 'Fair ', 3, 'Fair ', 3, 'Fair ', 3, 'Fair ', 3, 'Fair ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(85, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Sandra Ayot', 5, 'Excellent', 4, 'Good', 5, 'Very good', 5, 'Excellent', 4, 'Good', 4, 'Good', 5, 'Excellent', 5, 'Very good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:22:23', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Good', 5, 'Very good', 5, 'Very good', 4, 'Good', 5, 'Good', 4, 'Good', 4, 'Good', 4, 'Very good', 5, 'Excellent', 4, 'Good', 0, '', 0, '', 0, ''),
(86, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Innocent Lalam', 4, 'Good ', 3, 'Fair', 3, 'Fair', 4, 'Good ', 3, 'Fair ', 4, 'Good ', 4, 'Good', 2, 'Poor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:25:50', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair', 2, 'Poor', 3, 'Fair', 3, 'Better', 3, 'Better', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(87, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Semmy Adong', 4, 'Good ', 3, 'Fair', 2, 'Poor', 4, 'Good', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:29:17', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fair', 4, 'Good ', 3, 'Fair', 3, 'Fair', 3, 'Fair', 3, 'Fair', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(88, 12, 'Alice Gladys Ssempala', 'approved', '2025-08-23', 'Flavia Ajalo', 4, 'Good ', 4, 'Good ', 3, 'Fair', 4, 'Good ', 4, 'Good', 4, 'Good ', 4, 'Good ', 4, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 12:32:44', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 4, 'Good ', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(89, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Concy Ajok', 4, 'Confident and openly shares', 4, 'Self aware', 3, 'Fairly okay. A member commented about her being short tempered.', 3, 'Grown', 4, 'Punctual', 5, 'Fully respects instructions', 4, 'Owns up to work', 5, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:30:28', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Moderate', 4, 'She performed well in the practicals', 3, 'Conscious'),
(90, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Flavia Ajalo', 4, 'Confident', 4, 'Good', 4, 'Stable', 4, 'She is mature', 4, 'Puctual', 4, 'Carefully follows through', 4, 'Responsible and owns up to her work', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:33:22', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Alert', 3, 'Increased knowledge though she wasn\'t fine during the practical class. So her participation was minimal', 4, 'Connscious'),
(91, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Harriet Asemo', 4, 'Confident', 4, 'Aware', 4, 'Stable', 4, 'Mature', 4, 'Punctual', 4, 'Follows instructions ', 3, 'Fairly good', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:36:10', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Fairly alert', 3, 'As evaluated from the demonstrations in her practicals', 4, 'Conscious'),
(92, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Innocent Lalam', 2, 'Barely shares in class', 2, 'Fair', 4, 'Stable', 2, 'Moderately mature', 4, 'Puntual', 1, 'Barely responds when asked but participated when teamed up with a colleague ', 2, 'Fair.', 3, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:39:10', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 2, 'Fairly alert', 3, 'Improving', 3, 'Improving'),
(93, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Pauline Awori Mary ', 5, 'Confident', 4, 'Aware', 5, 'Stable', 4, 'Strong mindset', 5, 'Good', 5, 'Good. She actively participates', 4, 'Owns up to her work', 5, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:41:11', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Alert', 4, 'Improved ', 3, 'Conscious '),
(94, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Robina Akao', 3, 'Fair. Shares more in her mother tongue', 4, 'Aware', 4, 'Strong', 3, 'Fairly okay', 3, 'Punctual ', 2, 'Fair because at times ther is language barrier', 3, 'Good', 3, 'Fairly okay', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:44:01', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Alert', 3, 'Improved since the practice', 3, 'Conscious '),
(95, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Sandra Ayot', 4, 'Active', 4, 'Strong', 5, 'Stable', 4, 'Mature', 4, 'Punctual ', 4, 'Good', 4, 'Good', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:46:47', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Alert', 4, 'Improving', 3, 'Improving'),
(96, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-08-26', 'Semmy Adong', 2, 'Fairly confident', 2, 'Fairly aware', 3, 'Stable', 3, 'Fairly mature', 4, 'Good', 4, 'Follows closely', 3, 'Good', 3, 'Fair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-26 15:49:11', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 3, 'Alert', 3, 'Improved', 2, 'Fairly conscious '),
(97, 14, 'Esther Akello', 'approved', '2025-08-25', 'Sandra Ayot', 4, 'Sandra is confident', 4, 'She is neat and smart', 4, 'Sandra is quiet and calm', 4, 'She is attentive and ready to learn new things', 4, 'She is okay, but needs to work more on this', 4, 'She is a good listener ', 4, 'I believe she is ready to work with little supervision', 5, 'She relates well with her peers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-27 05:24:43', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'She has learnt how to offer her support when needed', 5, 'She is able to interact with children in a friendly manner', 3, 'To be assessed ', 4, 'She is learning how to discipline children with caution', 4, 'She is able to engage and interact well with children', 4, 'Generally able to look out for good hygiene and health', 5, 'She is attentibe', 4, 'Organised and attentive ', 4, 'She is learning how to instruct better', 3, 'To be assessed.', 0, '', 0, '', 0, ''),
(98, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-08-26', 'Flavia Ajalo', 5, 'Good', 5, 'Good', 5, 'Good', 5, 'Excellent', 5, 'Very Good', 4, 'Good', 5, 'Very good', 5, 'Excellent', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-27 09:40:42', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good', 5, 'Very good', 5, 'Very good', 5, 'Good', 4, 'Good', 5, 'Very good', 5, 'Excellent', 5, 'Excellent', 5, 'Very good', 4, 'Fairly good', 0, '', 0, '', 0, ''),
(99, 15, 'Harriet Patience Nantambi Kirigoola', 'approved', '2025-09-27', 'Daphine Asero', 4, 'Confident', 4, 'Clearly self aware ', 4, 'Stable', 5, 'Grown', 4, 'Punctual', 4, 'Good', 5, 'Excellent', 5, 'Good ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-09-27 13:21:39', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Very alert', 3, 'Improved', 4, 'Improved'),
(100, 13, 'Faith Waiswa Uyungrwoth', 'approved', '2025-10-24', 'Fiona Ocwee', 4, 'Good', 3, 'Fairly good', 3, 'Fair', 5, 'Good', 5, 'Very good', 4, 'Good', 5, 'Very good', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-10-24 07:05:40', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 4, 'Good', 5, 'Very good', 4, 'Good', 5, 'Good', 5, 'Good', 5, 'Good', 5, 'Good', 5, 'Vert good', 5, 'Good', 5, 'Good', 0, '', 0, '', 0, ''),
(101, 13, 'Faith Waiswa Uyungrwoth', 'pending', '2025-10-28', 'Fiona Ocwee', 5, 'Very good', 5, 'Good', 5, 'Excellent', 5, 'Very good', 4, 'Good', 5, 'Very good', 5, 'Excellent', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-10-28 06:16:13', 5, 'Good', 5, 'Very good', 4, 'Good', 5, 'Good', 5, 'Good', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(102, 13, 'Faith Waiswa Uyungrwoth', 'pending', '2025-10-28', 'Phionah Ainembabazi', 5, 'Very good', 5, 'Good', 5, 'Very good', 5, 'Good', 5, 'Very good', 5, 'Very good', 5, 'Excellent', 4, 'Good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-10-28 06:41:36', 4, 'Good', 5, 'Good', 5, 'Good', 5, 'Very good', 5, 'Very good', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, ''),
(103, 13, 'Faith Waiswa Uyungrwoth', 'pending', '2025-10-28', 'Phionah Ainembabazi', 5, 'Very good', 5, 'Good', 5, 'Very good', 5, 'Excellent', 4, 'Good', 5, 'Very good', 5, 'Excellent', 5, 'Very good', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-10-28 07:32:10', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 0, '', 5, 'Excellent', 5, 'Very good', 5, 'Excellent', 5, 'Goos', 4, 'Fairly good', 5, 'Excellent', 5, 'Good', 5, 'Very good', 4, 'Fairly good in english ,but perfect in luganda', 3, 'Average', 0, '', 0, '', 0, '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `maid_evaluations`
--
ALTER TABLE `maid_evaluations`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_trainer` (`trainer_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `maid_evaluations`
--
ALTER TABLE `maid_evaluations`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
